---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "smi-conformance.name" . }}
  namespace: meshery
subjects:
- kind: ServiceAccount
  name: {{ include "smi-conformance.serviceAccount" . }}
  namespace: {{ include "smi-conformance.namespace" . }}
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io